[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Pinochle"
version = "0.1.0"
description = "A Python package for playing Pinochle"
authors = [{name = "Phil Hanna", email = "ph1204@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
dependencies = []

[tool.setuptools]
packages = ["pinochle"]

[tool.setuptools.package-dir]
"" = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]

